### ISSUE TITLE
Classificação ToDo

### ISSUE THREAD

**Issue by cleitondacosta** [MatheusSoares98/Data-Structures#1]
- [x] Ler M registros do arquivo para a memória
- [x] Selecionar, no array em memória, o registro r com menor chave
- [x] Gravar o registro r na partição de saída
- [x] Substituir, no array em memória, o registro r pelo próximo registro do arquivo de entrada
- [x] Caso a chave deste último seja menor do que a chave recém gravada, gravá-lo no reservatório e substituir, no array em memória, o registro r pelo próximo registro do arquivo de entrada
- [x] Caso ainda exista espaço livre no reservatório, voltar ao passo 2
- [x] Caso contrário:
    - [x] fechar a partição de saída
    - [x] copiar os registros do reservatório para o array em memória
    - [x] esvaziar o reservatório
    - [x] abrir nova partição de saída
    - [x] voltar ao passo 2
