### ISSUE TITLE
Lefkowitz roadmap

### ISSUE THREAD

**Issue by MatheusSoares98** [MatheusSoares98/Data-Structures#2]
- [ ] passo 1 
    - [ ] abrir arqivo original A1
    - [ ] criar arquivo A2
    - [ ] Copiar para este arquivo a Chave Primária (CP)- COD-e todas as
Chaves Secundárias (CSs)-idade- para as quais se deseja construir um
índice 
    - [ ] Inserir também uma coluna ED (Endereço de Disco) para cada
registro
    Estrutura resultante de A2: ED - CP - CSi....CSn  = ED - COD - idade

**Comment by cleitondacosta** [comment]
- [ ] Refatorar
    - [ ] Remover os arquivos write.c e read.c
        - Criar o arquivo io.h, que fornecerá a funcionalidade atual do write.c e read.c?
            - Com essa implementação, o arquivo A1 e A2 terão que ser criados no início de toda execução.

- [ ] Depurar
    - [ ] Adicionar funções para _printar_, de forma organizada, todo o processo do algoritmo.
        - Criar um arquivo debug.h que conterá tais funções?
